### ISSUE TITLE
This should really be in the Community folder

### ISSUE THREAD

**Issue by FossPrime** [Keyup/Magento-MassShipment#1]
I'm looking into the best way to do a small modification, skipping orders with more than one item.
I'd like to stay connected with the main repo.

It would be much easier to just override things i need with the local code folder... if it weren't being taken up by MassShipment.

Good extension btw.

**Comment by vojtagrec** [comment]
Good point, thanks. It started as a small customization for a customer, and we put these in `local`. I thought about moving it to `community` when we have packed it for Magento Connect. But actually there's no reason to not have it in `community` already, so I'll move it there when I have some spare time in the coming days.

**Comment by vojtagrec** [comment]
After all, why leave for later what I can do right now :smiley:
