### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by febrez** [Keyup/Magento-MassShipment#4]
Hello,

While settings ACL, there is an Access Denied while doing the Action on this URL : 

/admin/keyupShipment/massShipEmail/

Is the method isAllowed() missing ?

Thank you for the fix

**Comment by kerstner-both** [comment]
Hello, you need to add 

/**
     \* Allow controller to be called by default.
     \* @return boolean
     */
    protected function _isAllowed() {
        return true;
    }

in Keyup_MassShipment_Adminhtml_KeyupShipmentController.

Best,
Matthias

**Comment by febrez** [comment]
I've made pull request to add a specific role, more flexible.

**Comment by kerstner-both** [comment]
Alright thanks, I would have pushed the same solution otherwise ;)
